---
name: module3_task1
on:
  push:
    branches:
      - main
  schedule:
  - cron: '0 0 * * *'
jobs:
  module3_task1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: cd in to correct directory
        run: |
          cd module3_task1
          make help
          
      - name: build
        run : |
         cd module3_task1
         make build
      
      - name: post
        run : |
          cd module3_task1
          make post
          
      - name: lint
        run: |
          cd module3_task1
          make lint
          
      - name: help
        run: |
           cd module3_tak1
           make help
