---
name: module3_task2
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'
jobs:
  module3_task2:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Hugo
        run: |
          cd module3_task2
          sudo ./setup.sh
      - name: build
        run: |
         cd module3_task2
         make build
      - name: post
        run: |
          cd module3_task2
          make POST_TITLE="Test Title" POST_NAME="Test-name" post
      - name: lint
        run: |
          cd module3_task2
          make lint
      - name: help
        run: |
           cd module3_task2
           make help
      - name: clean
        run: |
           cd module3_task2
           make clean
